apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgresql/
- api-node/
- client-react/
- Ingress.yaml

namespace: microservices-demo

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize

images:
- name: entransistor/api-node
  newName: entransistor/api-node
  newTag: 724a043daf95d12c70016f8292203d5d5a974304
- name: entransistor/client-react
  newName: entransistor/client-react
  newTag: 724a043daf95d12c70016f8292203d5d5a974304
- name: postgres
  newName: postgres
  newTag: 16-alpine

replicas:
- count: 2
  name: api-node
- count: 1
  name: client-react
