apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgresql/
- api-node/
- client-react/
- Ingress.yaml

namespace: microservices-demo

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize


replicas:
- count: 2
  name: api-node
- count: 1
  name: client-react
