apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: microservices-demo
  labels:
    app: api-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - name: api-node
        image: entransistor/api-node:fbf1db9b137a336056ff83b02aa99a795d9fdca2
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: DB_HOST
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: DB_NAME
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
