apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react
  namespace: microservices-demo
  labels:
    app: client-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react
  template:
    metadata:
      labels:
        app: client-react
    spec:
      containers:
      - name: client-react
        image: entransistor/client-react:486108d602ae76663c39d6958137f3d209bd2cc7
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
