apiVersion: v1
kind: Service
metadata:
  name: client-react
  namespace: microservices-demo
  labels:
    app: client-react
spec:
  type: ClusterIP
  selector:
    app: client-react
  ports:
  - port: 8765
    targetPort: 8765
    name: http
