apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - HService.yaml
  - StateFulSet.yaml
  - PGSecret.yaml
  - PGConfigMap.yaml
  - MigrationSQLJob.yaml
  - AutoScalingVPA.yaml
