apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: microservices-demo
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres-0.postgres -U admin -d mydb; do
            echo "Waiting for postgres...";
            sleep 2;
          done
          echo "PostgreSQL is ready!"
      containers:
      - name: migration
        image: entransistor/postgres-migrations:646d8a9effb93cf89aa2c91a33ee90b666f5552f
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: migration-secret
              key: DATABASE_URL
