apiVersion: v1
kind: Secret
metadata:
  name: migration-secret
  namespace: microservices-demo
type: Opaque
stringData:
  DATABASE_URL: "postgres://admin:secret123@postgres-0.postgres.microservices-demo.svc.cluster.local:5432/mydb?sslmode=disable"
