apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup-sa
  namespace: kube-system
  annotations:
   
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/microservices-demo-etcd-backup-role"
  labels:
    app: etcd-backup
