apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: microservices-demo
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret123
  POSTGRES_DB: mydb
  DB_USER: admin
  DB_PASSWORD: secret123
  DB_NAME: mydb
  DATABASE_URL: "postgresql://admin:secret123@postgres-0.postgres.microservices-demo.svc.cluster.local:5432/mydb?sslmode=disable"
